# Generated by Django 5.2 on 2025-04-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('manager', 'Manager')], default='customer', help_text='Defines the role of the user in the system.', max_length=10, verbose_name='Role'),
        ),
    ]
