# Generated by Django 5.2 on 2025-05-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', help_text='Defines the role of the user in the system.', max_length=10, verbose_name='Role'),
        ),
    ]
