# Generated by Django 5.2 on 2026-04-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('bazar_organizer', 'Bazar organizer')], default='buyer', help_text='Defines the role of the user in the system.', max_length=20, verbose_name='Role'),
        ),
    ]
