# Generated by Django 5.2 on 2025-12-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_by_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='deleted_by_seller',
            field=models.BooleanField(default=False),
        ),
    ]
