# Generated by Django 5.2 on 2025-12-16 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('shops', '0002_alter_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopvisit',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_visits', to='shops.shop'),
        ),
    ]
