# Generated by Django 5.2 on 2025-04-18 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shopName', models.CharField(max_length=100, unique=True)),
                ('shopDescription', models.TextField(max_length=1000)),
                ('shopAddress', models.CharField(max_length=300)),
                ('shopNumber', models.CharField(max_length=20)),
                ('shopEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
