# Generated by Django 5.2 on 2025-06-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'رقم الهاتف'), ('email', 'البريد الإلكتروني')], default='phone', max_length=10, verbose_name='وسيلة التواصل'),
        ),
    ]
