# Generated by Django 5.2 on 2025-06-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_contact_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], default='phone', max_length=10, verbose_name='وسيلة التواصل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Order Status'),
        ),
    ]
