# Generated by Django 5.2 on 2025-12-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Order Status'),
        ),
    ]
