# Generated by Django 5.2 on 2025-06-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_shop'),
        ('shops', '0002_alter_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop'),
            preserve_default=False,
        ),
    ]
