# Generated by Django 5.2 on 2025-12-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDescription',
            field=models.TextField(default='No description', max_length=2000),
            preserve_default=False,
        ),
    ]
